### ISSUE TITLE
Is this module part of tachyons?

### ISSUE THREAD

**Issue by pixelastic** [mrmrs/css-cursors#1]
Hello,

I was looking for utility classes for handling the cursor in tachyons.css but couldn't find anything in the doc. I then found this module, and the README references tachyons, but neither the repo name nor the classes seems to follow the tachyons convention.

I would be interested in having it included in tachyons if it's not already. Let me know if I can help i any way, or if I simply missed something in the tachyons doc.

**Comment by mrmrs** [comment]
This is not a part of tachyons - but it does use the tachyons-cli module.

**Comment by pixelastic** [comment]
Do you plan on making it part of tachyons at some point in the future?

**Comment by mrmrs** [comment]
No I do not, but this module would be very easy for you to add to your own tachyons build. It's very easy to add other css partials to the build, let me know if you need help with that.
