### ISSUE TITLE
Consider including `user-select` utilities

### ISSUE THREAD

**Issue by pixelastic** [mrmrs/css-cursors#2]
Hello,

I was looking for a way to prevent browsers to automatically select text when double-clicking. Turns out the `user-select: none` property can let you do that ([source](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select)). Do you think it would make sense to add it to this module?

The property still need some autoprefixer love currently, though.

**Comment by pixelastic** [comment]
Actually, `autoprefixer` does not handle `user-select` as it is not standard so the burden of writing the prefixes will be on us. ([source](https://github.com/postcss/autoprefixer/issues/167))

**Comment by mrmrs** [comment]
Hi @pixelastic - Thanks for inquiring about this. I don't generally take control away from the user or remove default functionality like this so I'm going to pass on adding user-select none but if that's something you need for your projects I'd just suggest just forking or copying this module to customizing it so it meets your needs.
